name: Deploy to Apache Server

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: '-avzr --delete'
        remote_path: '/home/geniusco/public_html/app.codepos.net'
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.REMOTE_KEY }}