name: Deploy to Apache Server

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.REMOTE_KEY }}

    - name: Install rsync
      run: sudo apt-get update && sudo apt-get install -y rsync

    - name: Deploy to Server
      run: |
        echo "PATH: $PATH"
        echo "rsync: $(which rsync)"
        rsync -avzr --delete -e 'ssh -o StrictHostKeyChecking=no' ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/geniusco/public_html/app.codepos.net